server:
  port: 8082

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: rest-user
          uri: http://localhost:9002
          predicates:
            - Path=/api/usuario/**
          filters:
            - AuthenticationFilter

        - id: servicio2
          uri: http://localhost:9003
          predicates:
            - Path=/api/reclamos/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka/
