server:
  port: 8082

spring:
  application:
    name: Gateway-Service
  cloud:
    gateway:
      routes:
        - id: rest-user
          uri: http://localhost:9002
          predicates:
            - Path=/api/usuario/**
          filters:
            - AuthenticationFilter

        - id: servicio2
          uri: http://localhost:9003
          predicates:
            - Path=/api/reclamos/**
          filters:
            - AuthenticationFilter
        - id: servicio3
          uri: http://localhost:9006
          predicates:
            - Path=/api/operaciones/**
          filters:
            - AuthenticationFilter
        - id: servicio4
          uri: http://localhost:9005
          predicates:
            - Path=/api/respuestas/**
          filters:
            - AuthenticationFilter
